/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import java.util.Stack;

/**
 *
 * @author HP
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Jframe
     */
    
    boolean error = false;
    public Calculator() {
        initComponents();
    }
    
    public boolean DotFound () {
        boolean found = false;
        String out = screen.getText();
        if(out.contains(".")) {
            found = true;
        }
        else {
            found = false;
        }
        
        return found;
    }
    public boolean OptFound() {
        boolean found = false;
        String out = screen.getText();
        if(out.charAt(out.length() - 1) == '/' || out.charAt(out.length() - 1) == '*' || out.charAt(out.length() - 1) == '-' || out.charAt(out.length() - 1) == '+') {
            found = true;
        }
        else {
            found = false;
        }
        
        return found;
    }
    public void Calculate() {
        String out = screen.getText();
        char c = out.charAt(out.length()-1);
        char o = '\0';
        if(c == '+' || c == '-' || c == '*' || c == '/') {
            out =  "SYNTAX ERROR!";
            screen.setText(out);
            error = true;
            return;
        }
        Stack<Double> number = new Stack<Double>();
        Stack<Character> opt = new Stack<Character>();
        String n = ""; double num;
        for(int i = 0; i < out.length(); i++) {
            c = out.charAt(i);
            if(c != '+' && c != '-' && c != '*' && c != '/') {
                n = n + c;
                if(i == out.length() - 1){
                    num = Double.parseDouble(n);
                    number.push(num);
                    while(!opt.empty()) {
                        o = opt.pop();
                        double n1 = number.pop();
                        double n2 = number.pop(),n3;
                        if(o == '+') {
                            n3 = n2 + n1;
                        }
                        else if(o == '-') {
                            n3 = n2 - n1;
                        }
                        else if(o == '*') {
                            n3 = n2 * n1;
                        }
                        else{
                            n3 = n2 / n1;
                        }
                        number.push(n3);
                    }
                }
                continue;
            }
            num = Double.parseDouble(n);
            number.push(num);
            n="";
            if(!opt.empty()){
                o = opt.peek();
                if(o == '/') {
                    opt.pop();
                    opt.push(out.charAt(i));
                    double n1 = number.pop();
                    double n2 = number.pop();
                    double n3 = n2 / n1;
                    number.push(n3);
                }
                else if(o == '*') {
                    if(c == '/') {
                        opt.push(c);
                    }
                    else{
                        opt.pop();
                        opt.push(c);
                        double n1 = number.pop();
                        double n2 = number.pop();
                        double n3 = n2 * n1;
                        number.push(n3);
                    }
                }
                else if(o == '+') {
                    if(c == '/' || c == '*' ) {
                        opt.push(c);
                    }
                    else{
                        opt.pop();
                        opt.push(c);
                        double n1 = number.pop();
                        double n2 = number.pop();
                        double n3 = n2 + n1;
                        number.push(n3);
                    }
                }
                else if(o == '-'){
                    opt.push(c);
                }
            }
            else{
                opt.push(c);
            }
        }
        out = Double.toString(number.peek());
        outscreen.setText(out);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        screen = new javax.swing.JLabel();
        n1 = new javax.swing.JButton();
        n0 = new javax.swing.JButton();
        ne = new javax.swing.JButton();
        n4 = new javax.swing.JButton();
        n8 = new javax.swing.JButton();
        nd = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        ndi = new javax.swing.JButton();
        nm = new javax.swing.JButton();
        ns = new javax.swing.JButton();
        na = new javax.swing.JButton();
        n9 = new javax.swing.JButton();
        n7 = new javax.swing.JButton();
        n6 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        X = new javax.swing.JButton();
        outscreen = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(300, 320));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 320));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        n1.setText("1");
        n1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n1MouseClicked(evt);
            }
        });
        jPanel1.add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 40, 40));

        n0.setText("0");
        n0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n0MouseClicked(evt);
            }
        });
        n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n0ActionPerformed(evt);
            }
        });
        jPanel1.add(n0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 40, 40));

        ne.setText("=");
        ne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                neMouseClicked(evt);
            }
        });
        jPanel1.add(ne, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 40, 40));

        n4.setText("4");
        n4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n4MouseClicked(evt);
            }
        });
        jPanel1.add(n4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 40, 40));

        n8.setText("8");
        n8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n8MouseClicked(evt);
            }
        });
        jPanel1.add(n8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 40, 40));

        nd.setText(".");
        nd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ndMouseClicked(evt);
            }
        });
        jPanel1.add(nd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 40, 40));

        n2.setText("2");
        n2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n2MouseClicked(evt);
            }
        });
        jPanel1.add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 40, 40));

        n3.setText("3");
        n3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n3MouseClicked(evt);
            }
        });
        jPanel1.add(n3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 40, 40));

        ndi.setText("/");
        ndi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ndiMouseClicked(evt);
            }
        });
        jPanel1.add(ndi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 40, 40));

        nm.setText("*");
        nm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmMouseClicked(evt);
            }
        });
        jPanel1.add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 40, 40));

        ns.setText("-");
        ns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nsMouseClicked(evt);
            }
        });
        jPanel1.add(ns, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 40, 40));

        na.setText("+");
        na.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                naMouseClicked(evt);
            }
        });
        jPanel1.add(na, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 40, 40));

        n9.setText("9");
        n9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n9MouseClicked(evt);
            }
        });
        jPanel1.add(n9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 40, 40));

        n7.setText("7");
        n7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n7MouseClicked(evt);
            }
        });
        jPanel1.add(n7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 40, 40));

        n6.setText("6");
        n6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n6MouseClicked(evt);
            }
        });
        jPanel1.add(n6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 40, 40));

        n5.setText("5");
        n5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                n5MouseEntered(evt);
            }
        });
        jPanel1.add(n5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 40, 40));

        X.setText("X");
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
        });
        jPanel1.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));
        jPanel1.add(outscreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n0ActionPerformed

    private void n0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n0MouseClicked
        // TODO add your handling code here:
        if(error) {
            screen.setText("");
            error = false;
        }
        if(screen.getText().length() < 27){
            String out = screen.getText();
            out = out + "0";
            screen.setText(out);
        }
    }//GEN-LAST:event_n0MouseClicked

    private void ndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ndMouseClicked
        // TODO add your handling code here:
        if(screen.getText().length() < 27){
            if(!DotFound()) {
                String out = screen.getText();
                out = out + ".";
                screen.setText(out);
            }
        }
    }//GEN-LAST:event_ndMouseClicked

    private void naMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naMouseClicked
        // TODO add your handling code here:
        if(screen.getText().length() < 27 && !OptFound()){
            String out = screen.getText();
            out = out + "+";
            screen.setText(out);
        }
    }//GEN-LAST:event_naMouseClicked

    private void n7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n7MouseClicked
        // TODO add your handling code here:
        if(error) {
            screen.setText("");
            error = false;
        }
        if(screen.getText().length() < 27){
            String out = screen.getText();
            out = out + "7";
            screen.setText(out);
        }
    }//GEN-LAST:event_n7MouseClicked

    private void n8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n8MouseClicked
        // TODO add your handling code here:
        if(error) {
            screen.setText("");
            error = false;
        }
        if(screen.getText().length() < 27){
            String out = screen.getText();
            out = out + "8";
            screen.setText(out);
        }
    }//GEN-LAST:event_n8MouseClicked

    private void n9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n9MouseClicked
        // TODO add your handling code here:
        if(error) {
            screen.setText("");
            error = false;
        }
        if(screen.getText().length() < 27){
            String out = screen.getText();
            out = out + "9";
            screen.setText(out);
        }
    }//GEN-LAST:event_n9MouseClicked

    private void ndiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ndiMouseClicked
        // TODO add your handling code here:
        if(screen.getText().length() < 27 && !OptFound()){
            String out = screen.getText();
            out = out + "/";
            screen.setText(out);
        }
    }//GEN-LAST:event_ndiMouseClicked

    private void n4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n4MouseClicked
        // TODO add your handling code here:
        if(error) {
            screen.setText("");
            error = false;
        }
        if(screen.getText().length() < 27){
            String out = screen.getText();
            out = out + "4";
            screen.setText(out);
        }
    }//GEN-LAST:event_n4MouseClicked

    private void n5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_n5MouseEntered

    private void n5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n5MouseClicked
        // TODO add your handling code here:
        if(error) {
            screen.setText("");
            error = false;
        }
        if(screen.getText().length() < 27){
            String out = screen.getText();
            out = out + "5";
            screen.setText(out);
        }
    }//GEN-LAST:event_n5MouseClicked

    private void n6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n6MouseClicked
        // TODO add your handling code here:
        if(error) {
            screen.setText("");
            error = false;
        }
        if(screen.getText().length() < 27){
            String out = screen.getText();
            out = out + "6";
            screen.setText(out);
        }
    }//GEN-LAST:event_n6MouseClicked

    private void nmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmMouseClicked
        // TODO add your handling code here:
        if(screen.getText().length() < 27 && !OptFound()){
            String out = screen.getText();
            out = out + "*";
            screen.setText(out);
        }
    }//GEN-LAST:event_nmMouseClicked

    private void n1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n1MouseClicked
        // TODO add your handling code here:
        if(error) {
            screen.setText("");
            error = false;
        }
        if(screen.getText().length() < 27){
            String out = screen.getText();
            out = out + "1";
            screen.setText(out);
        }
    }//GEN-LAST:event_n1MouseClicked

    private void n2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n2MouseClicked
        // TODO add your handling code here:
        if(error) {
            screen.setText("");
            error = false;
        }
        if(screen.getText().length() < 27){
            String out = screen.getText();
            out = out + "2";
            screen.setText(out);
        }
    }//GEN-LAST:event_n2MouseClicked

    private void n3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n3MouseClicked
        // TODO add your handling code here:
        if(error) {
            screen.setText("");
            error = false;
        }
        if(screen.getText().length() < 27){
            String out = screen.getText();
            out = out + "3";
            screen.setText(out);
        }
    }//GEN-LAST:event_n3MouseClicked

    private void nsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nsMouseClicked
        // TODO add your handling code here:
        if(screen.getText().length() < 27 && !OptFound()){
            String out = screen.getText();
            out = out + "-";
            screen.setText(out);
        }
    }//GEN-LAST:event_nsMouseClicked

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        // TODO add your handling code here:
        if(screen.getText().length() < 27){
            String out = screen.getText();
            if (out != null && out.length() > 0) {
                out = out.substring(0, out.length() - 1);
            }
            screen.setText(out);
        }
    }//GEN-LAST:event_XMouseClicked

    private void neMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_neMouseClicked
        // TODO add your handling code here:
            Calculate();
    }//GEN-LAST:event_neMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton X;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton n0;
    private javax.swing.JButton n1;
    private javax.swing.JButton n2;
    private javax.swing.JButton n3;
    private javax.swing.JButton n4;
    private javax.swing.JButton n5;
    private javax.swing.JButton n6;
    private javax.swing.JButton n7;
    private javax.swing.JButton n8;
    private javax.swing.JButton n9;
    private javax.swing.JButton na;
    private javax.swing.JButton nd;
    private javax.swing.JButton ndi;
    private javax.swing.JButton ne;
    private javax.swing.JButton nm;
    private javax.swing.JButton ns;
    private javax.swing.JLabel outscreen;
    private javax.swing.JLabel screen;
    // End of variables declaration//GEN-END:variables
}
